### ISSUE TITLE
TypedSlot-Class should be merged into TypedSlot

### ISSUE THREAD

**Issue by hogoww** [juliendelplanque/TypedSlot#1]
Shouldn't it?

It only adds one method, and more importantly, it's necessary to run the tests inside TypedSlot-tests. 
Making TypedSlot unusable (ish) on its on.

**Comment by juliendelplanque** [comment]
Nope, I split it on purpose so one can load the minimal amount of code. :-)

So indeed, it is not possible to use only TypedSlot package but on the other hand, one can use TypedSlot only with class or trait if needed.

So I think it will stay like that for the sake of modularity.
